### PR TITLE
Fix: stack too deep in LibDiamondHelper

### LINKED ISSUE #20: Fix: stack too deep in LibDiamondHelper
**Issue:**
During the generation of LibDiamondHelper, we encountered a "stack too deep" error when trying to load multiple arrays of function selectors into memory. This issue arises when there's an excessive amount of local variables or nested operations, causing the stack to exceed its limit.

**Proposed Solution:**
To resolve this issue, I've modified the code to reuse the same memory position for the arrays of function selectors. By writing these arrays to a consistent memory location, we can efficiently manage memory usage and prevent the "stack too deep" error.

### PR DESCRIPTION
**Pull request by kevin-fruitful**
Closes #20

### CODE REVIEW

File: test/common-build-steps.ts [hunk 1]
```diff
@@ -198,21 +198,21 @@ function setData(Data calldata d) external;`,
...
+f[0] = IDiamondProxy.getInts.selector;
+f[1] = IDiamondProxy.getData.selector;
 cut[0] = IDiamondCut.FacetCut({
   facetAddress: address(new ExampleFacet()),
   action: IDiamondCut.FacetCutAction.Add,
-  functionSelectors: f0
+  functionSelectors: f
 });
 
 bytes4[] memory f1 = new bytes4[](1);
```
Comment (hiddentao) [inline test/common-build-steps.ts:210]: This doesn't seem quite right - why are we initialising `f1` if we don't use it below? Also, does this work, i.e. can we re-initialise `f` to a new dynamic array and everything is copied into the cut struct?

Comment (kevin-fruitful) [reply test/common-build-steps.ts]: just pushed a fix, test is passing now:
```
  Command: build() - Foundry
    with multiple facets and methods with custom structs
      ✔ generates test helper (2571ms)


  1 passing (3s)
```
